name: Update AI News

on:
  schedule:
    # UTC 기준 매 4시간마다(00,04,08,12,16,20 UTC) → KST 09,13,17,21,01,05
    - cron: '0 */4 * * *'

jobs:
  crawl-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser openai

      - name: Fetch AI News
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/fetch_ai_news.py \
            --output news/$(date +'%Y-%m-%d %H:%M').md \
            --max-items 10

      - name: Commit & Push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add news/*.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: update AI news summary for $(date +'%Y-%m-%d %H:%M')"
            git push
          else
            echo "No changes to commit, skipping."
          fi
